### ISSUE TITLE
Audio segment for 1:4 is incorrect for recitation: 1

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [quran/quran.com-api#222]
[Api](http://staging.quran.com:3000/api/v3/chapters/1/verses?recitation=1&translations=21&language=en&offset=3&limit=1&text_type=words) returns single segment even though there are 4 words:
```json
{
  "id": 4,
  "verse_number": 4,
  "chapter_id": 1,
  "verse_key": "1:4",
  "text_madani": "مَٰلِكِ يَوْمِ ٱلدِّينِ",
  "text_indopak": "مٰلِكِ يَوۡمِ الدِّيۡنِؕ‏",
  "text_simple": "مالك يوم الدين",
  "audio": {
    "url": "verses/AbdulBaset/Mujawwad/mp3/001004.mp3",
    "duration": 7,
    "segments": [
      [
        "0",
        "1",
        "5650",
        "7250"
      ]
    ],
    "format": "mp3"
  }
};
```

**Comment by OrkhanAlikhanov** [comment]
It seems the data is provided by [quran-align](https://github.com/cpfair/quran-align) tool. I've detected many issues in recitation 1. Unfortunately, the tool does not seem to be well maintained or having high accuracy.

**Comment by Syahrul** [comment]
Salam, seems like this issue is still there. This is my first time using this API and seems related to this issue or maybe I'm wrong.

Verse 1:4 has 1 segment only for reciter id 1 & 2.

https://api.quran.com/api/v4/verses/by_chapter/1?fields=text_uthmani&audio=1
https://api.quran.com/api/v4/verses/by_chapter/1?fields=text_uthmani&audio=2

Reciter id 3 has 3 segments.
https://api.quran.com/api/v4/verses/by_chapter/1?fields=text_uthmani&audio=3
