### ISSUE TITLE
add language as a parameter passed to the search query

### ISSUE THREAD

**Issue by sharabash** [quran/quran.com-api#26]
this would limit the number of indexes searched and speed up search; also it would return more relevant results; consider a search for term 'god' as an example of what we don't want
![result](https://cloud.githubusercontent.com/assets/21639/13981389/82e68060-f0ec-11e5-8431-03c79abdc6d9.png)

**Comment by naveed-ahmad** [comment]
+1

**Comment by theonejb** [comment]
Salam,
 First of all, just wanted to say you people are doing an amazing job with the Quran.com site (and related projects) and may Allah bless you all.

Next, I wanted to see if this was something I could get involved in. I have recently started taking an interest in the study of the Quran, and after benefiting from the site a bunch of times I would love if I could contribute back.

I have 2 years of experience with Elasticsearch, and was wondering if this issue was something I could help with. If you want further details about my experience and how I think I might be able to contribute I'd love to chat.

Looking forwarding to hearing from you.
Regards,
Jibran

**Comment by mmahalwy** [comment]
@theonejb thanks so much for the kind note and we do need help! As a start, I'd suggest getting on our slack: https://quranslack.herokuapp.com/

We are in the midst of releasing v3 of the api and search is the last thing.

**Comment by naveed-ahmad** [comment]
done: https://github.com/quran/quran.com-api/pull/130
