### ISSUE TITLE
translation bug 

### ISSUE THREAD

**Issue by szcomanche** [quran/quran.com-api#333]
Surah 29 , verse 58 ... The recitation is wrong as it is including fews words which is not there is the ayah... Please correct as soon as possible... Verily Allah knows the best.... Jazak Allah khairan

**Comment by benomaire** [comment]
Sorry can you explain a bit more?
do you mean audio? the default reciter? `Mishari Rashid al-Afasy`?

**Comment by szcomanche** [comment]
Yes ,the default reciter. 
If you go through the text along with the continuous audio of reciter Mishari Rashid al-Afasy, there is extra words being recited...

**Comment by benomaire** [comment]
If that is what you mean, then yes, he is repeating the words underlined in blue, to start from a complete sentence starting from
لنبوئنهم
which is better than starting from 
غرفا
roughly like it is better to start in English from "We will surely" instead of starting from "chambers"

![333](https://user-images.githubusercontent.com/69304392/116094353-23340a00-a6b0-11eb-9005-b2a9248dd4f9.png)


To the best of my knowledge, ideally, since there are no stop marks in this ayah, a reciter should not stop to take breath before finishing the Ayah, but if he can't, then he has to keep as complete sentences as possible. Check other reciters to see how they recite this Ayah.

Probably, we should support moving the highlighting color back if the reciter repeats some words in the same Ayah, some time in the future :)
جزاكم الله خيرا

**Comment by szcomanche** [comment]
Thanks for the explaining it so beautifully.. I might have skipped... May
Allah reward you with goodness...!!!!

**Comment by AbirRazzak** [comment]
Closing issue since it seems to be resolved.
