### ISSUE TITLE
The full URL of the audio file, or at least the base url of the data 

### ISSUE THREAD

**Issue by mg4u** [quran/quran.com-api#352]
Hi all,
I have a small question, what is the full URL of the audio files of the verses, as the response is a relative path

**Comment by tahirmq1** [comment]
Salam, you can use:  "https://audio.qurancdn.com/" + ayah.audio.url

I am using v4 by the way

**Comment by mg4u** [comment]
> Salam, you can use: "https://audio.qurancdn.com/" + ayah.audio.url
> 
> I am using v4 by the way

Thanks a lot,
Another question plz, is there available audio files for Saad-Elghamdy for verses 💯

**Comment by ahmedre** [comment]
Salam 3alaikum,
Please don't rely on the audio.qurancdn.com - please use verses.quran.com instead.

The reason is because the qurancdn url is cloudflare,and audio should not go through cloudflare according to their terms, so we will probably be removing this url in the near future in sha' Allah to avoid having our account closed down.

Walsalam 3alaikum
