### ISSUE TITLE
missing harakah

### ISSUE THREAD

**Issue by telluriumsilver** [quran/quran.com-api#358]
As salaamu alaikum,
On surah 39 ayah 37, there is a harakah missing on the noon. All of the fonts do not have it.
This is on Quran.com:
![incorrect](https://user-images.githubusercontent.com/84548852/119063878-b4d92380-b99f-11eb-9227-6553844d5d4d.png)

This is on https://tafsirq.com/en/39-az-zumar/verse-37
![correct](https://user-images.githubusercontent.com/84548852/119063894-c1f61280-b99f-11eb-8a03-e1cd1a69d20b.png)

Jazakallah Khairun, and May Allah bless your efforts ameen.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
there is no harakah on the noon in any versions of the King Fahd print of the mushaf - I checked all 3 prints, so quran.com not showing a harakah on the noon is correct.
jazakumAllah khairan,
walsalam 3alaikum

**Comment by naushervan** [comment]
> As salaamu alaikum,
> On surah 39 ayah 37, there is a harakah missing on the noon. All of the fonts do not have it.
> This is on Quran.com:
> ![incorrect](https://user-images.githubusercontent.com/84548852/119063878-b4d92380-b99f-11eb-9227-6553844d5d4d.png)
> 
> This is on https://tafsirq.com/en/39-az-zumar/verse-37
> ![correct](https://user-images.githubusercontent.com/84548852/119063894-c1f61280-b99f-11eb-8a03-e1cd1a69d20b.png)
> 
> Jazakallah Khairun, and May Allah bless your efforts ameen.

Wa-ʿalaykumus salām brother. For your information, adding to brother @ahmedre 's comment, there is a reason WHY King Fahd print does not add a ḥarakah on the noon here. If you learn the Sunnah art of proper Qurʾān recitation, called Tajweed, you will understand this concept. Basically, the noon here is to be recited with a "Ghunnah" (hiding and prolonging the noon sound nasally) in proper Qurʾān recitation, and the King Fahd print indicates when to do this by not putting a ḥarakah. The sukoon ḥarakah is used whenever we are supposed to pronounce the noon clearly without prolonging it, i.e., without a Ghunnah. If you play the audio of this verse, you will be able to hear the Ghunnah on noon being done here.

Compare this to verse [111:2](https://quran.com/111/2) where there is a ḥarakah present on the noon. Play its audio and you will see that the noon being pronounced without Ghunnah (short and clearly spoken).

I personally appreciate and prefer the King Fahd Qurʾān script because they have this extra pronunciation information embedded in their script that people knowledgeable of the science of Qurʾān recitation can appreciate.

For learning more about the Sunnah art of beautifying Qurʾān recitation, see some short online resources here:

The Noble Emissaries: Learn Tajweed with Yasir Qadhi
https://www.youtube.com/playlist?list=PL30ADC4D586F46B2F

Learn Tajweed the Easy Way - 3 Minute Series - English
https://www.youtube.com/playlist?list=PL62RQxDpIL7UAWIf4ZHOH5aJIt3YHc7rg

Learn Tajweed the Easy Way - 3 Minute Series - Urdu
https://www.youtube.com/playlist?list=PL62RQxDpIL7UwbxX6uzFzMLsk_Yfk5EUs

However, for learning Tajweed properly, you will need to learn it from your Masjid Qārī who has himself learned Tajweed. So that he can provide you live feedback and correct your mistakes and pronunciation. It's not very difficult to learn if you already know how to read Arabic. And then you can yourself recite the Qurʾān beautifully and properly like a professional Qārī, in-shāʾAllāh.

**Comment by ahmedre** [comment]
jazakum Allah khairan @naushervan.

Brother @benomaire informed me, jazahuAllah khair, that the naskh script does indeed have a sukoon on top of the noon here, as seen [here](https://android.quran.com/data/naskh/width_1280/page463.png). this bug is therefore valid only for the "IndoPak text" - the other fonts are fine.

**Comment by naushervan** [comment]
You are right, brother @ahmedre : the Indo-Pak Naskh script does not include/encode this Tajweed-related pronunciation information in its script. All of the noon sākin have a ḥarakah on them, irrespective of the Ghunnah requirement.

**Comment by telluriumsilver** [comment]
> You are right, brother @ahmedre : the Indo-Pak Naskh script does not include/encode this Tajweed-related pronunciation information in its script. All of the noon sākin have a ḥarakah on them, irrespective of the Ghunnah requirement.

Yes you are right, see at Quran.com it shows:
![5F4C0CD7-9403-4784-ABAD-79774112255B](https://user-images.githubusercontent.com/84548852/122300226-a873b800-cec4-11eb-8e86-dee9318d693d.jpeg)

But in the Indopak Quran attached above it shows:
![94F3B558-DA3F-4025-8701-48C4CF472FB1](https://user-images.githubusercontent.com/84548852/122300265-b590a700-cec4-11eb-925f-093c5f163239.jpeg)

so therefore the Harakah is missing on the noon sakin and needs to be fixed inn shaa Allah because it is impossible to read in indopak without that since I am used to seeing the harakah on the noon sakin in my Quran copies at home.

**Comment by naveed-ahmad** [comment]
Closing, this was fixed few months ago https://quran.com/39:37
